### ISSUE TITLE
Update guide to accommodate Windows 10 October 1809 Update

### ISSUE THREAD

**Issue by teusink** [teusink/Home-Security-by-W10-Hardening#19]
Update guide to accommodate Windows 10 October 1809 Update

- ~~Clipboard~~
- ~~AutoPlay (it is on again after upgrade)~~
- ~~Phone~~
- ~~For developers~~
- Registry differences between 1803 and 1809

**Comment by teusink** [comment]
AutoPlay (it is on again after upgrade) --> just rerun REG-files.

**Comment by teusink** [comment]
Phone --> Nothing changes since 1803

**Comment by teusink** [comment]
For developers --> No need for config in regard to Security / Privacy here

**Comment by teusink** [comment]
Clipboard --> Added.

**Comment by optomux** [comment]
This is actually very very very good.

**Comment by teusink** [comment]
@optomux Hi, thanks for your compliment! Really appreciated!

**Comment by teusink** [comment]
Done.
