### ISSUE TITLE
Forgot to add a comment in hklm-cis-chrome.reg file at 1.1.15 (L2) line.

### ISSUE THREAD

**Issue by mnirun** [teusink/Home-Security-by-W10-Hardening#22]
Hello,

I believe you forgot  to add a comment in [hklm-cis-chrome.reg](https://github.com/teusink/Home-Security-by-W10-Hardening/blob/master/files/hklm-cis-chrome.reg#L88) file at 1.1.15 (L2) line.

`1.1.15 (L2) Ensure 'Allow invocation of file selection dialogs' is set to 'Enabled'
;[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
; <deleted> = (Default)
; 0000000 = Off
; 0000001 = On (CIS)
; NON-COMPLIANCE TO NOT DISRUPT COMMON HOME FEATURES
;"AllowFileSelectionDialogs"=dword:0000001`

Best regards,
Nirun M.

**Comment by teusink** [comment]
Indeed, thanks for notifying me and fixed ofcourse!
