### ISSUE TITLE
EncryptionMethodWithXtsFdv not specified & Limit Direct Memory Access replacement

### ISSUE THREAD

**Issue by kekkc** [teusink/Home-Security-by-W10-Hardening#26]
Hi,

thx for https://github.com/teusink/Home-Security-by-W10-Hardening/blob/master/files/hklm-cis-bitlocker.reg

Just 2 additions:
- EncryptionMethodWithXtsFdv is not specified (default for external backup drives is 128bit): https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.VolumeEncryption::EncryptionMethodWithXts_Name

- Limit Direct Memory Access (DMA) attacks (CIS) is no longer necessary. This was replaced by "DisableExternalDMAUnderLock" (however I would add a comment for this one that it should be set BEFORE bitlocker is enabled, otherwise drives can no longer be automatically unlocked and trying to change a password results in an error "0x80070490 "Element not found""): https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.VolumeEncryption::DisableExternalDMAUnderLock_Name

**Comment by teusink** [comment]
Hi @kekkc . Thanks for your suggestions!

In regard to _Limit Direct Memory Access (DMA) attacks (CIS)_, does this implicate that the key should be removed also, or really just a comment? In addition to adding _DisableExternalDMAUnderLock_ that is.

**Comment by kekkc** [comment]
yes, I would remove "Limit Direct Memory Access (DMA) attacks (CIS)" that is only looking up a CSID. DisableExternalDMAUnderLock should work in any case (even if CSIDS will eventually change or new ones introduced).
Should cover all cases when someone physically connects a thunderbold / DMA capable device when the PC is locked.

**Comment by teusink** [comment]
Just checked the file, and I see this. It is already commented out with the remark "NON-COMPLIANCE TO NOT DISRUPT COMMON HOME FEATURES". So that is covered.

```
;;; 18.8.7.1.2 (BL) Ensure 'Prevent installation of devices that match any of these device IDs: Prevent installation of devices that match any of these device IDs' is set to 'PCI\CC_0C0A'
;[HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DeviceInstall\Restrictions]
; <deleted> = (Default)
; 0000000 = Off
; PCI\CC_0C0A = Limit Direct Memory Access (DMA) attacks (CIS)
; NON-COMPLIANCE TO NOT DISRUPT COMMON HOME FEATURES
;"1"="PCI\CC_0C0A"
```

**Comment by teusink** [comment]
In regard to _EncryptionMethodWithXtsFdv_. I have added that, and also went from CBC-AES to XTS-AES.

Another question, Microsoft changed from default hardware encryption to software encryption. This while CIS still chooses hardware of software encryption.

What is your view on this?

**Comment by kekkc** [comment]
Cool.

Regarding hardware or software encryption, I'd stick for software currently for Bitlocker. Seems there are some wrong hardware firmware implementations of AES with many SSDs. Have only briefly seen it on https://www.heise.de/security/meldung/Windows-Sicherheit-Bitlocker-vermeidet-zukuenftig-Hardware-Verschluesselung-4543170.html (in german). Several months back there were always some tests by universities or "chaos computer club" that were able to break hw encryption on several SSDs.

Translates: 
Because hardware based encryption of discs regularly contained immense security problems, Microsoft is going to end it. Beginning with cumulative updates from 24.09. windows owned disc encryption bitlocker will ignore those functions by default...

**Comment by kekkc** [comment]
Safer than bitlocker might be open source / veracrypt / LUKS.

However, at some point you get to a discussion that reminds me about this:
http://imgs.xkcd.com/comics/security.png ;)

**Comment by teusink** [comment]
Hi @kekkc ! Sorry for slow response, busy schedules and all. Really thanks for your insights. I'll change this repo to software i.s.o. hardware encryption.

And that GIF is so true haha :smile:

**Comment by teusink** [comment]
I'll do the rest from this issue: https://github.com/teusink/Home-Security-by-W10-Hardening/issues/25
